name: gh-pages publisher 🚀

on:
  push:
    branches: [ source ]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 12

      - name: Install deps
        run: npm ci
      
      - name: Build
        run: git config user.name "<user name>" && git config user.email "user email"
        run: npm run deploy
        env:
          GH_TOKEN: ${{secrets.GH_PAGE_SECRET}}